version: '3'

services:
   backend:
      build: ./backend
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./backend/:/usr/src/app/
      ports:
        - 8000:8000
      env_file:
        - ./.env
      depends_on:
        - migration   

   frontend:
      build: ./frontend
      ports:
        - 3000:3000 
      stdin_open: true 

   migration:
      build: ./backend
      command: python manage.py migrate
      env_file:
        - ./.env
      depends_on:
        - db

   db:
      image: postgres:12.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=hello_django
        - POSTGRES_PASSWORD=hello_django
        - POSTGRES_DB=hello_django_dev

volumes:
 postgres_data:
