version: '3.3'
services:
   backend:
      container_name: backend_django
      build: ./backend
      ports:
         - 8002:8000
      links:
         - db
      command: python /code/manage.py runserver
      depends_on:
         - db
   
   db:
      container_name: db
      image: postgres:12.0-alpine
      environment:
         - POSTGRES_DB=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
     

volumes:
   postgres_data: